[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run db:migrate:deploy && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
